---
- name: Combine default and additional folders
  set_fact:
    all_folders_to_check: "{{ default_folders_to_check | combine(additional_folders_to_check, recursive=True) }}"
  when: additional_folders_to_check is defined

- name: Default to only default folders if no additional ones are provided
  set_fact:
    all_folders_to_check: "{{ default_folders_to_check }}"
  when: additional_folders_to_check is not defined

- name: Check folder existence and permissions
  debug:
    msg: "Checking folder {{ item.path }} with permissions {{ item.permissions }}"
  loop: "{{ all_folders_to_check }}"

- name: Validate folder existence
  ansible.builtin.stat:
    path: "{{ item.path }}"
  register: folder_stat
  loop: "{{ all_folders_to_check }}"

- name: Fail if folder does not exist
  ansible.builtin.fail:
    msg: "Folder {{ item.path }} does not exist"
  when: not folder_stat.results[item_index].stat.exists
  loop_control:
    index_var: item_index

- name: Validate folder permissions
  ansible.builtin.assert:
    that:
      - folder_stat.results[item_index].stat.mode == item.permissions
    fail_msg: "Folder {{ item.path }} does not have correct permissions"
  loop_control:
    index_var: item_index